server:
  port: 8000
  
spring:
  application:
    name: proxy
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    backend:
      path: /guestbook/**
      #url: http://localhost:8080/guestbook/   use this to define hard coded URLs
      service-id: backend # uses eureka service name
      strip-prefix: false  #keeps the URL prefix "/guestbook" before redirecting to backend
      
    frontend:
      path: /**
      #url: http://localhost:8081/
      service-id: frontend
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds 15000


