server:
  port: 8000
  
spring:
  application:
    name: proxy
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    backend:
      path: /guestbook/**
      url: http://localhost:8080/guestbook/
      
    frontend:
      path: /**
      url: http://localhost:8081/